"""PDF Safety Report Generator for Codex.

Generates professional safety compliance reports with weather data,
citations, and AI recommendations.
"""

from datetime import datetime
from io import BytesIO
from typing import Any, Dict, List, Optional

from fpdf import FPDF


class SafetyReportPDF(FPDF):
    """Custom PDF class for safety reports."""
    
    def header(self):
        """Add header to each page."""
        # Logo or title area
        self.set_font('Arial', 'B', 16)
        self.set_text_color(33, 37, 41)
        self.cell(0, 10, 'Codex - Safety Compliance Report', 0, 1, 'C')
        
        # Subtitle
        self.set_font('Arial', '', 10)
        self.set_text_color(108, 117, 125)
        self.cell(0, 5, 'AI-Powered Operational Risk Assessment', 0, 1, 'C')
        
        # Line separator
        self.line(10, 30, 200, 30)
        self.ln(10)
    
    def footer(self):
        """Add footer to each page."""
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Codex on {datetime.now().strftime("%Y-%m-%d %H:%M")}', 0, 0, 'C')
    
    def chapter_title(self, title: str):
        """Add a chapter title."""
        self.set_font('Arial', 'B', 14)
        self.set_text_color(33, 37, 41)
        self.cell(0, 10, title, 0, 1, 'L')
        self.ln(2)
    
    def chapter_body(self, body: str):
        """Add chapter body text."""
        self.set_font('Arial', '', 11)
        self.set_text_color(33, 37, 41)
        self.multi_cell(0, 6, body)
        self.ln()
    
    def add_decision_box(self, can_proceed: bool, reasoning: str):
        """Add a highlighted decision box."""
        if can_proceed:
            # Green box for safe
            self.set_fill_color(212, 237, 218)
            self.set_draw_color(40, 167, 69)
            self.set_text_color(21, 87, 36)
            status_text = 'SAFE TO PROCEED'
        else:
            # Red box for unsafe
            self.set_fill_color(248, 215, 218)
            self.set_draw_color(220, 53, 69)
            self.set_text_color(114, 28, 36)
            status_text = 'DO NOT PROCEED'
        
        # Draw box
        self.set_font('Arial', 'B', 14)
        self.cell(0, 12, status_text, 1, 1, 'C', True)
        
        # Add reasoning below
        self.set_font('Arial', '', 10)
        self.set_text_color(33, 37, 41)
        self.multi_cell(0, 6, reasoning)
        self.ln(5)
    
    def add_weather_section(self, weather_data: Dict[str, Any]):
        """Add weather conditions section."""
        self.chapter_title('Weather Conditions')
        
        if not weather_data:
            self.chapter_body('Weather data not available for this location.')
            return
        
        # Current conditions table
        self.set_font('Arial', 'B', 11)
        self.cell(60, 8, 'Current Conditions:', 0, 1)
        
        self.set_font('Arial', '', 10)
        current = weather_data.get('current', {})
        
        if current:
            conditions = [
                ('Temperature', f"{current.get('temperature_2m', 'N/A')}°C"),
                ('Wind Speed', f"{current.get('wind_speed_10m', 'N/A')} km/h"),
                ('Wind Gusts', f"{current.get('wind_gusts_10m', 'N/A')} km/h"),
                ('Precipitation', f"{current.get('precipitation', 'N/A')} mm"),
                ('Humidity', f"{current.get('relative_humidity_2m', 'N/A')}%"),
            ]
            
            for label, value in conditions:
                self.cell(50, 6, f'{label}:', 0, 0)
                self.cell(0, 6, str(value), 0, 1)
        
        self.ln(5)
        
        # Compliance status
        compliance = weather_data.get('compliance_status', 'Unknown')
        self.set_font('Arial', 'B', 11)
        self.cell(60, 8, f"Compliance Status: {compliance}", 0, 1)
        
        # Violations if any
        violations = weather_data.get('violations', [])
        if violations:
            self.set_font('Arial', 'B', 10)
            self.cell(0, 6, 'Violations Detected:', 0, 1)
            self.set_font('Arial', '', 10)
            for v in violations[:3]:  # Show first 3
                date = v.get('date', 'Unknown date')
                issues = ', '.join(v.get('issues', []))
                self.cell(10, 5, '-', 0, 0)
                self.multi_cell(0, 5, f"{date}: {issues}")
        
        self.ln(5)
    
    def add_citations_section(self, citations: List[Dict[str, Any]]):
        """Add document citations section."""
        self.chapter_title('Document Citations')
        
        if not citations:
            self.chapter_body('No specific document citations available.')
            return
        
        for i, citation in enumerate(citations[:5], 1):  # Show first 5
            self.set_font('Arial', 'B', 10)
            filename = citation.get('filename', 'Unknown')
            self.cell(0, 6, f"[{i}] {filename}", 0, 1)
            
            self.set_font('Arial', '', 9)
            self.set_text_color(108, 117, 125)
            relevance = citation.get('relevance_score', 'N/A')
            self.cell(0, 5, f"Relevance Score: {relevance}", 0, 1)
            
            self.set_text_color(33, 37, 41)
            text_preview = citation.get('text_preview', '')
            if text_preview:
                # Truncate if too long
                if len(text_preview) > 300:
                    text_preview = text_preview[:300] + '...'
                self.multi_cell(0, 5, text_preview)
            
            self.ln(3)
    
    def add_recommendations_section(self, recommendations: List[str]):
        """Add AI recommendations section."""
        self.chapter_title('AI Recommendations')
        
        if not recommendations:
            self.chapter_body('No specific recommendations at this time.')
            return
        
        self.set_font('Arial', '', 11)
        for i, rec in enumerate(recommendations, 1):
            self.cell(10, 6, f'{i}.', 0, 0)
            self.multi_cell(0, 6, rec)
        
        self.ln(5)


def generate_safety_report(
    site_location: str,
    operation_type: str,
    decision: Any,
) -> BytesIO:
    """Generate a PDF safety report.
    
    Args:
        site_location: The site location
        operation_type: Type of operation
        decision: SafetyDecision object with all the data
        
    Returns:
        BytesIO containing the PDF
    """
    pdf = SafetyReportPDF()
    pdf.add_page()
    
    # Report metadata
    pdf.set_font('Arial', '', 10)
    pdf.set_text_color(108, 117, 125)
    pdf.cell(0, 6, f"Report Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", 0, 1)
    pdf.cell(0, 6, f"Site: {site_location}", 0, 1)
    pdf.cell(0, 6, f"Operation: {operation_type.title()}", 0, 1)
    pdf.ln(5)
    
    # Decision section
    pdf.chapter_title('Safety Decision')
    pdf.add_decision_box(
        can_proceed=decision.can_proceed,
        reasoning=decision.reasoning
    )
    
    # Weather section
    if decision.weather_compliance:
        # Combine current conditions with compliance data
        weather_data = {
            **decision.weather_compliance,
            'current': decision.current_conditions.get('current', {}) if decision.current_conditions else {}
        }
        pdf.add_weather_section(weather_data)
    
    # Citations section
    if decision.citations:
        pdf.add_citations_section(decision.citations)
    
    # Recommendations section
    if decision.recommendations:
        pdf.add_recommendations_section(decision.recommendations)
    
    # Memory updates section
    if decision.new_memories:
        pdf.add_page()
        pdf.chapter_title('Memory Updates')
        pdf.set_font('Arial', '', 10)
        for mem in decision.new_memories:
            mem_type = mem.get('type', 'unknown').title()
            content = mem.get('content', '')
            pdf.cell(10, 6, '-', 0, 0)
            pdf.multi_cell(0, 6, f"{mem_type}: {content}")
        pdf.ln(5)
    
    # Save to BytesIO
    pdf_bytes = BytesIO()
    pdf.output(pdf_bytes)
    pdf_bytes.seek(0)
    
    return pdf_bytes


def get_weather_trend_analysis(
    weather_client,
    site_location: str,
    days: int = 7,
) -> List[Dict[str, Any]]:
    """Analyze weather trends for the next N days.
    
    Args:
        weather_client: OpenMeteoClient instance
        site_location: Location to check
        days: Number of days to analyze
        
    Returns:
        List of daily safety assessments
    """
    location_data = weather_client.geocode_location(site_location)
    if not location_data:
        return []
    
    forecast = weather_client.get_forecast(
        latitude=location_data['latitude'],
        longitude=location_data['longitude'],
        days=days,
        hourly=False,
        daily=True
    )
    
    daily_data = forecast.get('daily', {})
    dates = daily_data.get('time', [])
    max_wind = daily_data.get('wind_speed_10m_max', [])
    max_gusts = daily_data.get('wind_gusts_10m_max', [])
    precipitation = daily_data.get('precipitation_sum', [])
    weather_codes = daily_data.get('weather_code', [])
    
    trend_analysis = []
    for i, date in enumerate(dates):
        wind = max_wind[i] if i < len(max_wind) else 0
        gusts = max_gusts[i] if i < len(max_gusts) else 0
        rain = precipitation[i] if i < len(precipitation) else 0
        code = weather_codes[i] if i < len(weather_codes) else 0
        
        # Simple safety assessment
        issues = []
        if wind > 20:  # 20 mph threshold
            issues.append(f"High winds ({wind:.1f} km/h)")
        if gusts > 30:  # 30 mph gust threshold
            issues.append(f"Strong gusts ({gusts:.1f} km/h)")
        if rain > 5:  # 5mm rain threshold
            issues.append(f"Heavy rain ({rain:.1f} mm)")
        if code in [95, 96, 99]:  # Thunderstorm codes
            issues.append("Thunderstorms")
        
        trend_analysis.append({
            'date': date,
            'wind_speed': wind,
            'wind_gusts': gusts,
            'precipitation': rain,
            'weather_code': code,
            'is_safe': len(issues) == 0,
            'issues': issues
        })
    
    return trend_analysis
